config/routes.rb
Freddiepettersson::Application.routes.draw do

  resources :places, :only => [:index, :show]

  resources :jobs, :only => [:index, :show]

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :pages, :only => [:index, :show]

  root :controller => "pages", :action => "show", :id => "home"

  match "contact", :controller => "pages", :action => "show", :id => "contact"
  match "bio", :controller => "pages", :action => "show", :id => "bio"

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end
# == Schema Information
#
# Table name: admin_users
#
#  id                     :integer         not null, primary key
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(128)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer         default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

app/models/job.rb
class Job < ActiveRecord::Base
  include ActionView::Helpers::DateHelper
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :place

  attr_accessible :title, :description, :started_at, :ended_at, :place

  validates :place, :presence => true
  validates :title, :presence => true
  validates :started_at, :presence => true
  # Get the working period as properly formatted string (:started_at - :ended_at)
  # Only showing year and month. The word "Present" is used if :ended_at is null.
  def period
    "#{self.started_at.strftime('%B %Y')} - #{self.ended_at.blank? ? "Present" : self.ended_at.strftime('%B %Y')}"
  end

  # Get the working period length as properly formatted string
  def period_length
    distance_of_time_in_words(self.ended_at.blank? ? DateTime.now : self.ended_at, self.started_at.prev_month)
  end
end
# == Schema Information
#
# Table name: jobs
#
#  id          :integer         not null, primary key
#  title       :string(255)     not null
#  description :text
#  started_at  :date            not null
#  ended_at    :date
#  place_id    :integer
#  created_at  :datetime
#  updated_at  :datetime
#  slug        :string(255)
#

app/models/page.rb
class Page < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  # Setup accessible attributes
  attr_accessible :title, :content
  # Last updated at (formatted)
  def last_updated_at
    self.updated_at.to_s(:rfc822)
  end
end
# == Schema Information
#
# Table name: pages
#
#  id         :integer         not null, primary key
#  title      :string(255)     not null
#  content    :text
#  created_at :datetime
#  updated_at :datetime
#  slug       :string(255)
#

app/models/place.rb
class Place < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_many :jobs, :dependent => :destroy

  attr_accessible :title, :location, :website, :jobs

  validates :title, :presence => true
  validates :location, :presence => true
end
# == Schema Information
#
# Table name: places
#
#  id         :integer         not null, primary key
#  title      :string(255)     not null
#  location   :string(255)     not null
#  website    :string(255)
#  created_at :datetime
#  updated_at :datetime
#  slug       :string(255)
#

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/jobs_controller.rb
class JobsController <  InheritedResources::Base
  actions :index, :show
  respond_to :html, :xml, :json
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  # GET /pages/1
  def show
    @page = Page.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end
end

app/controllers/places_controller.rb
class PlacesController < InheritedResources::Base
  actions :index, :show
  respond_to :html, :xml, :json
end

app/helpers/application_helper.rb
module ApplicationHelper
  include TweetButton
  def app_title
    "freddiepettersson"
  end

  # Set the page title
  def title(page_title)
    content_for(:title) { page_title }
  end

  def google_plus_one_button
    raw('<g:plusone annotation="inline"></g:plusone>')
  end

  # Get a facebook like button
  def facebook_like_button
    src = "http://www.facebook.com/plugins/like.php?href=#{CGI::escape(request.url)}&layout=standard&show_faces=true&width=450&action=like&font=arial&colorscheme=light&height=80"
    content_tag :iframe, nil, :src => src, :scrolling => 'no', :frameborder => '0',
    :allowtransparency => true, :id => :facebook_like
  end

  TweetButton.default_tweet_button_options = {:via => "punkrawkR87", :count => "horizontal"}

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/jobs/index.html.erb
<% title "Jobs" %>
<h2>Jobs</h2>
<p>
  This is a listing of my professional experience.
</p>
<table>
  <tr>
    <th>Title</th>
    <th>Company</th>
    <th>Period</th>
  </tr>
  <% @jobs.each do |job| %>
  <tr>
    <td><%= link_to job.title, job %></td>
    <td><%= link_to job.place.title, job.place %></td>
    <td><%= job.period %> (<%= job.period_length %>)</td>
  </tr>
  <% end %>
</table>

app/views/jobs/show.html.erb
<% title @job.title %>
<h2><%= @job.title %></h2>
<p>
  <b>Company:</b>
  <%= link_to @job.place.title, @job.place %>
</p>
<p>
  <b>Location:</b>
  <%= @job.place.location %>
</p>
<p>
  <b>Website:</b>
  <%= link_to @job.place.website, @job.place.website %>
</p>
<p>
  <b>Period:</b>
  <%= @job.period %> (<%= @job.period_length %>)
</p>
<p>
  <%= @job.description %>
</p>
<%= raw(disqus_thread) %>

app/views/layouts/_footer.html.erb
<footer>
  <nav id="footer-nav">
    <ul>
      <li>
        <%= link_to "Home", root_path %>
      </li>
      <li>
        <%= link_to "Contact", contact_path %>
      </li>
      <li>
        <%= link_to "Bio", bio_path %>
      </li>
    </ul>
  </nav>
  <p id="copyright-notes">
    <%= link_to app_title, root_path %> &copy; 2011 <%= mail_to "freddieboi@gmail.com", "Freddie Pettersson" %>
  </p>
  <div id="social">
    <div id="tweet-button">
      <%= tweet_button %>
    </div>
    <div id="plusone-button">
      <%= google_plus_one_button %>
    </div>
    <!--<div id="like-button">
    <%= facebook_like_button %>
    </div>-->
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div id="heading">
    <h1><%= link_to "Freddie Pettersson", root_path %></h1>
    <p>
      <em>Coffee, code, licorice and punkrawk!</em>
    </p>
    <%= image_tag "FreddiDroid.png", :size => "96x96" %>
  </div>
  <nav id="header-nav">
    <ul>
      <li>
        <%= link_to "Home", root_path %>
      </li>
      <li>
        <%= link_to "Contact", contact_path %>
      </li>
      <li>
        <%= link_to "Bio", bio_path %>
      </li>
      <li>
        <%= link_to "Jobs", jobs_path %>
      </li>
      <li>
        <%= link_to "Places", places_path %>
      </li>
      <li>
        <%= link_to "Admin", admin_dashboard_path %>
      </li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html itemscope itemtype="http://schema.org/Person">
  <head>
    <title>Freddie Pettersson<%= content_for?(:title) ? " - #{yield(:title)}" : ""%></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <link rel="shortcut icon" href="/favicon.ico" />
    <meta itemprop="name" content="Freddie Pettersson">
    <meta itemprop="description" content="Coffee, code, liquorice and punkrawk!">
  </head>
  <body>
    <%= render "layouts/header" %>

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, :class => "flash #{key}") %>
    <% end %>
    
    <section id="content">
      <%= yield %>
    </section>
    
    <%= render "layouts/footer" %>
    
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/index.html.erb
<% title "Pages" %>
<h2>Pages</h2>
<table>
  <tr>
    <th>Title</th>
    <th>Last Updated At</th>
  </tr>
  <% @pages.each do |page| %>
  <tr>
    <td><%= link_to page.title, page %></td>
    <td><%= page.last_updated_at %></td>
  </tr>
  <% end %>
</table>

app/views/pages/show.html.erb
<% title @page.title %>
<h2><%= @page.title %></h2>
<p class="content">
  <%= raw(@page.content) %>
</p>
<p class="date">
  <strong>Last Updated At:</strong>
  <%= @page.last_updated_at %>
</p>
<%= raw(disqus_thread) %>
 

app/views/places/index.html.erb
<% title "Places" %>
<h2>Places</h2>
<p>
  This is a listing of all the places I've experienced through jobs or education.
</p>
<table>
  <tr>
    <th>Title</th>
    <th>Location</th>
    <th>Website</th>
    <th>Jobs</th>
  </tr>
  <% @places.each do |place| %>
  <tr>
    <td><%= link_to place.title, place %></td>
    <td><%= place.location %></td>
    <td><%= link_to place.website, place.website %></td>
    <td><%= place.jobs.count %></td>
  </tr>
  <% end %>
</table>

app/views/places/show.html.erb
<% title @place.title %>
<h2><%= @place.title %></h2>
<p>
  <b>Location:</b>
  <%= @place.location %>
</p>
<p>
  <b>Website:</b>
  <%= link_to @place.website, @place.website %>
</p>
<h3>Jobs</h3>
<p>
  I've had <%= pluralize(@place.jobs.count, "job", "different jobs") %> at <%= link_to @place.title, @place %>.
</p>
<table>
  <tr>
    <th>Title</th>
    <th>Period</th>
  </tr>
  <% @place.jobs.each do |job| %>
  <tr>
    <td><%= link_to job.title, job %></td>
    <td><%= job.period %> (<%= job.period_length %>)</td>
  </tr>
  <% end %>
</table>
<%= raw(disqus_thread) %>